### PR TITLE
Fix #2

### LINKED ISSUE #2: macos's `trash' need "-F" arguments
Without "-F", the Finder cannot putback the trashed file.

### PR DESCRIPTION
**Pull request by wyuenho**
So trashed files can be put back.

### CODE REVIEW

**Comment by wyuenho** [comment]
@tarsius this is a super easy one, mind taking a look?

**Comment by tarsius** [comment]
The signature of this function is `(call-process PROGRAM &optional INFILE DESTINATION DISPLAY &rest ARGS)` and you propose this change:

```diff
-                         (call-process "trash" nil t nil file-name)
+                         (call-process "trash -F" nil t nil file-name)
```

but (assuming that adding `-F` is correct in the first place) this should be

```diff
-                         (call-process "trash" nil t nil file-name)
+                         (call-process "trash" nil t nil "-F" file-name)
```

**Comment by wyuenho** [comment]
`"trash -F"` works, but I've changed the call to fit the signature now.

**Comment by tarsius** [comment]
> `"trash -F"` works, but I've changed the call to fit the signature now.

Are you sure? This little experiment seems to confirm that that shouldn't be the case:

```
(call-process "echo hello" nil t nil)
=error=> Searching for program: No such file or directory, echo hello
```

**Comment by tarsius** [comment]
Thanks.

I improved the commit message.

**Pull request merged**
